{% set name = "reportlab" %}
{% set version = "3.5.52" %}
{% set sha256 = "a5ad4696987fdb42d976093e1b1a585ec2ad42634b5ce94dbb71362dcc758afb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pillow >=2.4.0
    - freetype
  run:
    - python
    - pillow >=2.4.0
    - freetype

test:
  imports:
    - reportlab
    - reportlab.graphics.charts
    - reportlab.graphics.samples
    - reportlab.graphics.widgets
    - reportlab.graphics.barcode
    - reportlab.graphics
    - reportlab.lib
    - reportlab.pdfbase
    - reportlab.pdfgen
    - reportlab.platypus

about:
  home: http://www.reportlab.com/opensource/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Open-source engine for creating complex, data-driven PDF documents and custom vector graphics
  doc_url: http://www.reportlab.com/documentation/

extra:
  recipe-maintainers:
    - mcs07
